import { expect, test } from "@playwright/test";
import { type Kind, openEditor, setCode } from "./helpers";

// CONTEXT.md's Validation rule: the code pane is judged by the REAL mermaid
// parser, not only by our hand-rolled one.
test("text our parser accepts but mermaid rejects is reported in the pane", async ({ page }) => {
  const editor = await openEditor(page, "Flowchart");
  // the user's bug: `subgraph` is a mermaid keyword, so `subgraph-1` cannot be
  // spelled as an edge endpoint — our parser reads it back happily, and the
  // codegen round-trips it, so nothing else in the app notices
  await setCode(editor, 'flowchart TB\n  a["A"]\n  subgraph subgraph-1["G"]\n  end\n  a --> subgraph-1\n');

  const rejection = editor.locator(".code-mermaid-error");
  await expect(rejection).toBeVisible({ timeout: 15_000 });
  await expect(rejection).toContainText("Mermaid.js");
  // it is not a gMermaid parse error: that pane stays empty
  await expect(editor.locator(".code-errors")).toHaveCount(0);
});

test("a diagram mermaid understands shows no rejection", async ({ page }) => {
  const editor = await openEditor(page, "Flowchart");
  await setCode(editor, 'flowchart TB\n  a["A"] --> b["B"]\n');
  // give the debounced validator time to answer before asserting the absence
  await expect(editor.locator(".cm-content")).toContainText("a --> b");
  await page.waitForTimeout(2_000);
  await expect(editor.locator(".code-mermaid-error")).toHaveCount(0);
});

// the other direction: code nobody typed. Every sample is generated by our own
// codegen, so mermaid refusing one means the codegen (or an id) is broken.
const KINDS: readonly Kind[] = ["Flowchart", "Sequence", "Class", "State", "Requirement", "Journey", "Timeline", "Gantt", "Mindmap", "Usecase"];
for (const kind of KINDS) {
  test(`mermaid accepts the generated code of the ${kind} sample`, async ({ page }) => {
    const editor = await openEditor(page, kind);
    await page.waitForTimeout(2_000); // let the debounced validator answer
    expect(await editor.locator(".code-mermaid-error").allInnerTexts()).toEqual([]);
  });
}
